// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError('DefaultFirebaseOptions not configured for Linux.');
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs0n_tmtciHHlRXf30XxVgrbC4-4TENzA',
    appId: '1:164074208933:web:6ad11b87de6817c298174c',
    messagingSenderId: '164074208933',
    projectId: 'rct-connect',
    authDomain: 'rct-connect.firebaseapp.com',
    storageBucket: 'rct-connect.firebasestorage.app',
    measurementId: 'G-KD1LR93RNS',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBV0NGHyaikr0pCzpT-2iyPOsNDh7QPp7s',
    appId: '1:164074208933:ios:c2987ba9d2ed7b4198174c',
    messagingSenderId: '164074208933',
    projectId: 'rct-connect',
    storageBucket: 'rct-connect.firebasestorage.app',
    iosClientId: '164074208933-agcoiag5l1voejoceso13rm249sma4oa.apps.googleusercontent.com',
    iosBundleId: 'com.example.runningClubTunis',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBV0NGHyaikr0pCzpT-2iyPOsNDh7QPp7s',
    appId: '1:164074208933:ios:c2987ba9d2ed7b4198174c',
    messagingSenderId: '164074208933',
    projectId: 'rct-connect',
    storageBucket: 'rct-connect.firebasestorage.app',
    iosClientId: '164074208933-agcoiag5l1voejoceso13rm249sma4oa.apps.googleusercontent.com',
    iosBundleId: 'com.example.runningClubTunis',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNAgAE_ULnrFPWdmG37PLX8OAFee7O3DY',
    appId: '1:164074208933:android:dea395827f930a8898174c',
    messagingSenderId: '164074208933',
    projectId: 'rct-connect',
    storageBucket: 'rct-connect.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBs0n_tmtciHHlRXf30XxVgrbC4-4TENzA',
    appId: '1:164074208933:web:434493da338e661698174c',
    messagingSenderId: '164074208933',
    projectId: 'rct-connect',
    authDomain: 'rct-connect.firebaseapp.com',
    storageBucket: 'rct-connect.firebasestorage.app',
    measurementId: 'G-BD68PF3BL5',
  );

}