// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

import 'package:flutter_dotenv/flutter_dotenv.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions not configured for Linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
        apiKey: dotenv.env['web_api_key']!,
        appId: dotenv.env['web_app_id']!,
        messagingSenderId: dotenv.env['web_messaging_sender_id']!,
        projectId: dotenv.env['web_project_id']!,
        authDomain: dotenv.env['web_auth_domain'],
        storageBucket: dotenv.env['web_storage_bucket'],
        measurementId: dotenv.env['web_measurement_id'],
      );

  static FirebaseOptions get macos => FirebaseOptions(
        apiKey: dotenv.env['macos_api_key']!,
        appId: dotenv.env['macos_app_id']!,
        messagingSenderId: dotenv.env['macos_messaging_sender_id']!,
        projectId: dotenv.env['macos_project_id']!,
        storageBucket: dotenv.env['macos_storage_bucket'],
        authDomain: dotenv.env['macos_auth_domain'],
        measurementId: dotenv.env['macos_measurement_id'],
        iosBundleId: 'com.example.runningClubTunis',
      );

  static FirebaseOptions get ios => FirebaseOptions(
        apiKey: dotenv.env['ios_api_key']!,
        appId: dotenv.env['ios_app_id']!,
        messagingSenderId: dotenv.env['ios_messaging_sender_id']!,
        projectId: dotenv.env['ios_project_id']!,
        storageBucket: dotenv.env['ios_storage_bucket'],
        authDomain: dotenv.env['ios_auth_domain'],
        measurementId: dotenv.env['ios_measurement_id'],
        iosClientId: dotenv.env['ios_client_id'],
        iosBundleId: 'com.example.runningClubTunis',
      );

  static FirebaseOptions get android => FirebaseOptions(
        apiKey: dotenv.env['android_api_key']!,
        appId: dotenv.env['android_app_id']!,
        messagingSenderId: dotenv.env['android_messaging_sender_id']!,
        projectId: dotenv.env['android_project_id']!,
        storageBucket: dotenv.env['android_storage_bucket'],
        authDomain: dotenv.env['android_auth_domain'],
        measurementId: dotenv.env['android_measurement_id'],
      );

  static FirebaseOptions get windows => FirebaseOptions(
        apiKey: dotenv.env['windows_api_key']!,
        appId: dotenv.env['windows_app_id']!,
        messagingSenderId: dotenv.env['windows_messaging_sender_id']!,
        projectId: dotenv.env['windows_project_id']!,
        storageBucket: dotenv.env['windows_storage_bucket'],
        authDomain: dotenv.env['windows_auth_domain'],
        measurementId: dotenv.env['windows_measurement_id'],
      );
}
